FROM $IMS_REPO

ADD configs/ims/ims-server.xml /usr/local/tomcat/conf/server.xml
ADD configs/ims/ims-config.groovy /usr/local/tomcat/.grails/ims-config.groovy
# For old images that run behalf on root account
ADD configs/ims/ims-config.groovy /root/.grails/ims-config.groovy
ADD hosts/ims/addHosts.sh /tmp/addHosts.sh

#Self-signed certificate instalation
ADD cert/$SSL_CRT /usr/local/share/ca-certificates/$SSL_CRT
RUN update-ca-certificates

COPY cert/$SSL_CRT $JAVA_HOME/lib/security/Huron.crt
RUN \
    cd $JAVA_HOME/lib/security \
    && keytool -keystore cacerts -storepass changeit -noprompt -trustcacerts -importcert -alias ldapcert -file $SSL_CRT
