FROM $NGINX_REPO

#Self-signed certificate instalation
ADD cert/$SSL_CRT /usr/local/share/ca-certificates/$SSL_CRT
RUN update-ca-certificates

# HTTPS Configuration
ADD cert/$SSL_CRT /etc/cert/$SSL_CRT
ADD cert/$SSL_KEY /etc/cert/$SSL_KEY
ADD configs/nginx/nginx.conf /usr/local/nginx/conf/nginx.conf
ADD configs/nginx/ssl.conf /usr/local/nginx/conf/ssl.conf
