version: '3'
services:
  memcached:
    container_name: memcached
    restart: unless-stopped
    build:
      context: ../Cytomine_bootstrap
      dockerfile: ../cytomine-docker-compose/docker/memcached/Dockerfile
    networks:
      - cytomine

  rabbitmq:
    container_name: rabbitmq
    restart: unless-stopped
    image: 782111260328.dkr.ecr.us-east-2.amazonaws.com/slidevault-rabbitmq:v1.0
    environment:
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - cytomine

  postgresql:
    container_name: postgresql
    restart: unless-stopped
    image: 782111260328.dkr.ecr.us-east-2.amazonaws.com/slidevault-postgis:v1.0.0
    #    mem_limit: 8g
    volumes:
      - postgis_data:/var/lib/postgresql:rw
    networks:
      - cytomine

  mongodb:
    container_name: mongodb
    restart: unless-stopped
    image: 782111260328.dkr.ecr.us-east-2.amazonaws.com/slidevault-mongodb:v1.0.0
    volumes:
      - mongodb_data:/data/db:rw
    networks:
      - cytomine

  slurm:
    container_name: slurm
    restart: unless-stopped
    hostname: cytomine-slurm
    build:
      context: ../Cytomine_bootstrap
      dockerfile: ../cytomine-docker-compose/docker/slurm/Dockerfile
    privileged: true
    volumes:
      - slurm_data:/var/lib/mysql:rw
      - singularity_images:/data/softwares/images:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      - cytomine

  iip_off:
    container_name: iipOff
    restart: unless-stopped
    build:
      context: ../Cytomine_bootstrap
      dockerfile: ../cytomine-docker-compose/docker/iipOff/Dockerfile
    depends_on:
      - memcached
    privileged: true
    environment:
      - NB_IIP_PROCESS=10
    volumes:
      - /data/images:/data/images:rw
    links:
      - memcached:memcached
    networks:
      - cytomine

  iip_cyto:
    container_name: iipCyto
    restart: unless-stopped
    build:
      context: ../Cytomine_bootstrap
      dockerfile: ../cytomine-docker-compose/docker/iipCyto/Dockerfile
    privileged: true
    depends_on:
      - memcached
    environment:
      - NB_IIP_PROCESS=10
    volumes:
      - /data/images:/data/images:rw
    links:
      - memcached:memcached
    networks:
      - cytomine

  bioformat:
    restart: unless-stopped
    container_name: bioformat
    image: 782111260328.dkr.ecr.us-east-2.amazonaws.com/slidevault-bioformat:v1.0.0
    environment:
      - BIOFORMAT_PORT=4321
    volumes:
      - /data/images:/data/images:rw
    networks:
      - cytomine

  web_ui:
    container_name: web_UI
    restart: unless-stopped
    build:
      context: ../Cytomine_bootstrap
      dockerfile: ../cytomine-docker-compose/docker/web_UI/Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - cytomine

  software_router:
    container_name: software_router
    restart: unless-stopped
    build:
      context: ../Cytomine_bootstrap
      dockerfile: ../cytomine-docker-compose/docker/software_router/Dockerfile
    privileged: true
    depends_on:
      - rabbitmq
      - slurm
    volumes:
      - singularity_images:/data/softwares/images
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - rabbitmq:rabbitmq
      - slurm:slurm
    networks:
      - cytomine

volumes:
  postgis_data: {}
  mongodb_data: {}
  slurm_data: {}
  singularity_images: {}

networks:
  cytomine:
#    name: cytomine