FROM cytomine/core:v3.2.3

ADD configs/core/cytomineconfig.groovy /usr/share/tomcat9/.grails/cytomineconfig.groovy
ADD hosts/core/addHosts.sh /tmp/addHosts.sh
ADD configs/core/server.xml /usr/local/tomcat/conf/server.xml
