FROM 782111260328.dkr.ecr.us-east-2.amazonaws.com/slidevault-hl7-bridge-msk:latest

ENV DB_HOST=postgresql
ENV HL7_SERVER_PORT=8888
ENV HL7_EPIC_HOST=140.163.170.109
ENV HL7_EPIC_PORT=17240
ENV HL7_EPIC_USE_TLS=false
ENV SLIDEVAULT_UI_URL=https://redhat.hurondigitalpathology.com/
