services:

  ims:
    restart: unless-stopped
#    image: cytomine/ims:latest_dev # for development purposes
    build:
      context: ../
      dockerfile: ./configs/ims/Dockerfile
    depends_on:
      - bioformat
    environment:
      - IMS_STORAGE_PATH=${IMS_STORAGE_PATH}
    volumes:
      - ${IMS_STORAGE_PATH}:${IMS_STORAGE_PATH}:rw
      - ${IMS_BUFFER_PATH}:/tmp/uploaded:rw
    networks:
      - slidevault
