services:
  memcached:
    container_name: memcached
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./configs/memcached/Dockerfile
    networks:
      - slidevault

  rabbitmq:
    container_name: ${RABBITMQ_CONTAINER_NAME}
    restart: unless-stopped
    image: ${RABBITMQ_REPO}
    environment:
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 10
    # ports:
    #   - 5672:5672
    #   - 15672:15672
    networks:
      - slidevault

  postgresql:
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: unless-stopped
    image: ${POSTGIS_REPO}
    #    mem_limit: 8g
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgis_data:/var/lib/postgresql:rw
    healthcheck:
      test: "exit 0"
    # ports:
    #   - 5432:5432
    networks:
      - slidevault

  mongodb:
    container_name: ${MONGODB_CONTAINER_NAME}
    restart: unless-stopped
    image: ${MONGODB_REPO}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INIT_DATABASE}
      MONGO_INIT_USERNAME: ${MONGO_INIT_USERNAME}
      MONGO_INIT_PASSWORD: ${MONGO_INIT_PASSWORD}
    volumes:
      - ../configs/mongo/init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - mongodb_data:/data/db:rw
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 30s
      retries: 10
    # ports:
    #   - 27017:27017
    networks:
      - slidevault

  slurm:
    container_name: ${SLURM_CONTAINER_NAME}
    restart: unless-stopped
    # hostname: cytomine-slurm
    build:
      context: ../
      dockerfile: configs/slurm/Dockerfile
    privileged: true
    volumes:
      - slurm_data:/var/lib/mysql:rw
      - singularity_images:/data/softwares/images:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      - slidevault

  iip_off:
    container_name: ${IIP_OFF_CONTAINER_NAME}
    restart: unless-stopped
    build:
      context: ../
      dockerfile: configs/iipOff/Dockerfile
    depends_on:
      - memcached
    privileged: true
    environment:
      - NB_IIP_PROCESS=${NB_IIP_PROCESS}
    volumes:
      - ${IMS_STORAGE_PATH}:${IMS_STORAGE_PATH}:rw
    links:
      - memcached:memcached
    networks:
      - slidevault

  iip_cyto:
    container_name: ${IIP_CYTO_CONTAINER_NAME}
    restart: unless-stopped
    build:
      context: ../
      dockerfile: configs/iipCyto/Dockerfile
    privileged: true
    depends_on:
      - memcached
    environment:
      - NB_IIP_PROCESS=${NB_IIP_PROCESS}
    volumes:
      - ${IMS_STORAGE_PATH}:${IMS_STORAGE_PATH}:rw
    links:
      - memcached:memcached
    networks:
      - slidevault

  bioformat:
    restart: unless-stopped
    container_name: ${BIOFORMAT_CONTAINER_NAME}
    image: ${BIOFORMAT_REPO}
    environment:
      - BIOFORMAT_PORT=${BIOFORMAT_PORT}
    volumes:
      - ${IMS_STORAGE_PATH}:${IMS_STORAGE_PATH}:rw
    networks:
      - slidevault

  software_router:
    container_name: ${SOFTWARE_ROUTER_CONTAINER_NAME}
    restart: unless-stopped
    build:
      context: ../
      dockerfile: configs/software_router/Dockerfile
    privileged: true
    depends_on:
      - rabbitmq
      - slurm
    volumes:
      - singularity_images:/data/softwares/images
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - rabbitmq:rabbitmq
      - slurm:slurm
    networks:
      - slidevault

volumes:
# Enable below to generate new volumes for container.
  postgis_data: {}
  mongodb_data: {}
  slurm_data: {}
  singularity_images: {}

# Enable below to re-use existing data volumes with docker compose.
  # postgis_data: 
  #   name: postgis_data
  #   external: true
  # mongodb_data:
  #   name: mongodb_data
  #   external: true
  # slurm_data: 
  #   name: slurm_data
  #   external: true
  # singularity_images: 
  #   name: singularity_images
  #   external: true

networks:
  slidevault:
#    name: cytomine
