services:
  ims:
    restart: unless-stopped
    image: ${IMS_SERVICE_REPO}
    container_name: ${IMS_SERVICE_CONTAINER_NAME}
    depends_on:
      bioformat:
        condition: service_started
      core:
          condition: service_healthy
    environment:
      IMS_STORAGE_PATH: ${IMS_STORAGE_PATH}
      IMS_SERVICE_ROOT_CONTEXT: ${IMS_SERVICE_ROOT_CONTEXT}
      SLIDEVAULT_CORE: http://${CORE_SERVICE_CONTAINER_NAME}:8080${CORE_SERVICE_ROOT_CONTEXT}
      IMS_SERVICE_EXTERNAL_HOSTNAME: ${SV_HTTP_PROTOCOL}://${SV_HOSTNAME}${IMS_SERVICE_ROOT_CONTEXT}
      IMS_SERVICE_INTERNAL_HOSTNAME: http://${IMS_SERVICE_CONTAINER_NAME}:8080${IMS_SERVICE_ROOT_CONTEXT}
      IIP_SERVER_HOSTNAME: http://${IIP_CYTO_CONTAINER_NAME}:80
      KEYCLOAK_HOSTNAME: http://${KEYCLOAK_CONTAINER_NAME}:8080${KEYCLOAK_ROOT_CONTEXT} #Dont change protocol here. Its container to container communication
      KEYCLOAK_SV_REALM: ${KEYCLOAK_SV_REALM}
      KEYCLOAK_SV_CLIENT_ID: ${KEYCLOAK_SV_CLIENT_ID}
      KEYCLOAK_SV_CLIENT_SECRET: ${KEYCLOAK_SV_CLIENT_SECRET}
      KEYCLOAK_SV_SERVICE_ACCOUNT_USERNAME: ${KEYCLOAK_SV_SERVICE_ACCOUNT_USERNAME}
      KEYCLOAK_SV_SERVICE_ACCOUNT_PASSWORD: ${KEYCLOAK_SV_SERVICE_ACCOUNT_PASSWORD}
    volumes:
      - ${IMS_STORAGE_PATH}:${IMS_STORAGE_PATH}:rw
      - ${IMS_BUFFER_PATH}:/tmp/uploaded:rw
    networks:
      - slidevault
    extra_hosts:
      - "${SV_HOSTNAME}:${SV_HOST_IP}"
