services:

  core:
    container_name: core
    restart: unless-stopped
    build:
      context: ../
      dockerfile: configs/core/Dockerfile
#    ports:
#      - 8080:8080
    depends_on:
      - postgresql
      - mongodb
      - rabbitmq
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${UPLOADED_SOFTWARES_PATH}:/data/softwares/code:rw
    networks:
      - slidevault

  nginx:
    container_name: nginx
    restart: unless-stopped
    build:
      context: ../
      dockerfile: configs/nginx/Dockerfile
    depends_on:
      - ims
      - iip_cyto
      - core
      - iip_off
      - web_ui
    volumes:
      - ${IMS_BUFFER_PATH}:/tmp/uploaded
    ports:
      - "80:80"
      - "443:443"
    networks:
      - slidevault
