services:
  memcached:
    container_name: memcached
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./configs/memcached/Dockerfile
    networks:
      - slidevault

  rabbitmq:
    container_name: rabbitmq
    restart: unless-stopped
    image: ${RABBITMQ_REPO}
    environment:
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - slidevault

  postgresql:
    container_name: postgresql
    restart: unless-stopped
    image: ${POSTGIS_REPO}
    #    mem_limit: 8g
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - postgis_data:/var/lib/postgresql:rw
    ports:
      - 5432:5432
    networks:
      - slidevault

  mongodb:
    container_name: mongodb
    restart: unless-stopped
    image: ${MONGODB_REPO}
    volumes:
      - mongodb_data:/data/db:rw
    ports:
      - 27017:27017
    networks:
      - slidevault

  slurm:
    container_name: slurm
    restart: unless-stopped
    hostname: cytomine-slurm
    build:
      context: ../
      dockerfile: configs/slurm/Dockerfile
    privileged: true
    volumes:
      - slurm_data:/var/lib/mysql:rw
      - singularity_images:/data/softwares/images:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      - slidevault

  iip_off:
    container_name: iipOff
    restart: unless-stopped
    build:
      context: ../
      dockerfile: configs/iipOff/Dockerfile
    depends_on:
      - memcached
    privileged: true
    environment:
      - NB_IIP_PROCESS=${NB_IIP_PROCESS}
    volumes:
      - ${IMS_STORAGE_PATH}:${IMS_STORAGE_PATH}:rw
    links:
      - memcached:memcached
    networks:
      - slidevault

  iip_cyto:
    container_name: iipCyto
    restart: unless-stopped
    build:
      context: ../
      dockerfile: configs/iipCyto/Dockerfile
    privileged: true
    depends_on:
      - memcached
    environment:
      - NB_IIP_PROCESS=${NB_IIP_PROCESS}
    volumes:
      - ${IMS_STORAGE_PATH}:${IMS_STORAGE_PATH}:rw
    links:
      - memcached:memcached
    networks:
      - slidevault

  bioformat:
    restart: unless-stopped
    container_name: bioformat
    image: ${BIOFORMAT_REPO}
    environment:
      - BIOFORMAT_PORT=${BIOFORMAT_PORT}
    volumes:
      - ${IMS_STORAGE_PATH}:${IMS_STORAGE_PATH}:rw
    networks:
      - slidevault

  web_ui:
    container_name: web_UI
    restart: unless-stopped
    build:
      context: ../
      dockerfile: configs/web_ui/Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - slidevault

  software_router:
    container_name: software_router
    restart: unless-stopped
    build:
      context: ../
      dockerfile: configs/software_router/Dockerfile
    privileged: true
    depends_on:
      - rabbitmq
      - slurm
    volumes:
      - singularity_images:/data/softwares/images
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - rabbitmq:rabbitmq
      - slurm:slurm
    networks:
      - slidevault

volumes:
# Enable below to generate new volumes for container.
  postgis_data: {}
  mongodb_data: {}
  slurm_data: {}
  singularity_images: {}

# Enable below to re-use existing data volumes with docker compose.
  # postgis_data: 
  #   name: postgis_data
  #   external: true
  # mongodb_data:
  #   name: mongodb_data
  #   external: true
  # slurm_data: 
  #   name: slurm_data
  #   external: true
  # singularity_images: 
  #   name: singularity_images
  #   external: true

networks:
  slidevault:
#    name: cytomine
